spring.application.name=SPRINGBOOT-SERVICE
server.port=8080

app.storage.upload-dir=src/main/resources/uploads
app.fastapi.ingest-url=http://localhost:8000/api/v1/ingest/upload
app.fastapi.process-url-template=http://localhost:8000/api/v1/ingest/{fileId}/process
app.fastapi.status-url-template=http://localhost:8000/api/v1/ingest/{fileId}/status
app.fastapi.chunks-url-template=http://localhost:8000/api/v1/ingest/{fileId}/chunks

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=health,info

